#if !defined(AFX_MK30COMM_H__EDB7B1B8_C7DD_4B1C_A23E_5CD15A66FCB4__INCLUDED_)
#define AFX_MK30COMM_H__EDB7B1B8_C7DD_4B1C_A23E_5CD15A66FCB4__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMk30Comm wrapper class

class CMk30Comm : public CWnd
{
protected:
	DECLARE_DYNCREATE(CMk30Comm)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xad027d26, 0xf975, 0x11d2, { 0x90, 0x23, 0x0, 0x40, 0xc7, 0x57, 0x73, 0x72 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetPassword();
	void SetPassword(LPCTSTR);
	CString GetRasPassword();
	void SetRasPassword(LPCTSTR);
	CString GetRasUserName();
	void SetRasUserName(LPCTSTR);
	CString GetUserName();
	void SetUserName(LPCTSTR);
	CString GetMyComputer();
	void SetMyComputer(LPCTSTR);
	short GetMachineStatus();
	void SetMachineStatus(short);
	BOOL GetPowerOn();
	void SetPowerOn(BOOL);
	CString GetVersion();
	void SetVersion(LPCTSTR);
	CString GetFtpUserName();
	void SetFtpUserName(LPCTSTR);
	CString GetFtpPassword();
	void SetFtpPassword(LPCTSTR);

// Operations
public:
	short Connect(LPCTSTR strMachineName);
	short DeleteFile(LPCTSTR strFileName);
	void Disconnect();
	short Execute(LPCTSTR strCommand);
	BOOL GetHistory(BSTR* strHistory);
	short GetLastError();
	void LogEnd();
	BOOL LogStart();
	BOOL GetOffset(BSTR* strOffset);
	void Pause(BOOL blnPause);
	short SendEmKey(LPCTSTR strKey);
	short SendFile(LPCTSTR strFileName);
	long GetVoltage();
	long GetElectricity();
	long GetFrequency();
	long GetFSpeed();
	long GetMaxFrequency();
	long GetSigOnMaxFrequency();
	long GetResistivity1();
	long GetResistivity2();
	long GetInch();
	long GetDigit();
	long GetCoordSys();
	long GetCoordOrg(long nCoordSys, double* pdblCoord);
	long GetMachCoord(double* pdblCoord);
	long GetCoord(long nCoordSys, double* pdblCoord);
	BOOL GetCondition(BSTR* strCondition);
	BOOL GetMachineKind(long* mainKind, long* subKind);
	short GetConditionType();
	short CreateNcCond(short nParamType, short DatabaseType, double* cnd, double* mchcon, double* mcb, double* ncProc, long* plnNcProcNum, long* fin, long* plnMTRL);
	long GetHiVersion(BSTR* pstrHiVersion);
	long GetRunningFileName(BSTR* pstrRunningFileName, long* pFilePathType);
	long GetRunningMainNcFileFirstLine(BSTR* pstrFirstLine);
	long GetNcFileRunEventTime(BSTR* pstrPrevEventTime, BSTR* pstrCurrentEventTime);
	short FtpSendFile(LPCTSTR strFileName);
	long GetCurrentLogonUserInfo(BSTR* pstrUserLoginName, BSTR* pstrUserName, BSTR* pstrUserNo, long* pUserLevel);
	long FarLogout(long* pError);
	long FarLogon(LPCTSTR strUserNo, LPCTSTR strPasswrod, long* pError);
	long GetUserLogonInfFile(LPCTSTR lpLocalFileFullPath);
	long GetMachineLock();
	long GetOffsetVar(long nOffsetNumber, double* dblOffsetValue);
	long SetMacroVar(long nMacroNumber, double dblMacroValue);
	long GetMacroVar(long nMacroNumber, double* dblMacroValue);
	long GetMacroVarRange(long nStartNo, long nEndNo, double* dblMacro);
	long GetMacroVarRangeSafeArray(long nStartNo, long nEndNo, VARIANT* varMacro);
	long SetMacroVarRange(long nStartNo, long nEndNo, double* dblMacro);
	long SetMacroVarRangeSafeArray(long nStartNo, long nEndNo, VARIANT* varMacro);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MK30COMM_H__EDB7B1B8_C7DD_4B1C_A23E_5CD15A66FCB4__INCLUDED_)
