//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by mocxtest.rc
//
#define IDGetRunningMainNcFileFirstLine 3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MOCXTEST_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_DLG_SEARCHCONDITION         129
#define IDC_COMBO_LQUID                 202
#define IDC_COMBO_WIREM                 203
#define IDC_COMBO_WRIDAM                204
#define IDC_COMBO_KIND                  205
#define IDC_COMBO_COMMENT               206
#define IDC_COMBO_OFSTAJST              207
#define IDC_COMBO_AIC                   208
#define IDC_COMBO_SFCC                  209
#define IDC_EDIT_PRECISION              210
#define IDC_COMBO_BSA                   211
#define IDC_COMBO_CUTN                  212
#define IDC_COMBO_LQKND                 213
#define IDC_COMBO_MATER                 214
#define IDC_COMBO_THICK                 215
#define IDC_COMBO_ROUGH                 216
#define IDC_COMBO_MTRL                  218
#define IDC_COMBO_BS                    219
#define IDS_ITEMNAMENEW0                220
#define IDS_ITEMNAMENEW1                221
#define IDS_ITEMNAMENEW2                222
#define IDS_ITEMNAMENEW3                223
#define IDS_ITEMNAMENEW4                224
#define IDS_ITEMNAMENEW5                225
#define IDS_ITEMNAMENEW6                226
#define IDS_ITEMNAMENEW7                227
#define IDS_ITEMNAMENEW8                228
#define IDS_ITEMNAMENEW9                229
#define IDS_ITEMNAMENEW10               230
#define IDS_ITEMNAMENEW11               231
#define IDS_ITEMNAMENEW12               232
#define IDS_ITEMNAMENEW13               233
#define IDS_ITEMNAMENEW14               234
#define IDS_ITEMNAMENEW15               235
#define IDS_ITEMNAMENEW16               236
#define IDC_COMM_STATUS                 1000
#define IDC_MACHINE_STATUS              1001
#define IDC_BUTTON1                     1002
#define IDC_EDIT1                       1003
#define IDC_EDIT2                       1004
#define IDC_EDIT3                       1005
#define IDC_EDIT4                       1006
#define IDC_EDIT5                       1007
#define IDC_BUTTON2                     1008
#define IDC_EDIT6                       1009
#define IDC_BUTTON3                     1010
#define IDC_BUTTON4                     1011
#define IDC_EDIT7                       1012
#define IDC_BUTTON5                     1013
#define IDC_EDIT8                       1014
#define IDC_BUTTON6                     1015
#define IDC_COMBO1                      1016
#define IDC_BUTTON7                     1017
#define IDC_EDIT10                      1018
#define IDC_BUTTON8                     1019
#define IDC_EDIT11                      1020
#define IDC_BUTTON9                     1021
#define IDC_PAUSE                       1022
#define IDC_RUN                         1023
#define IDC_BUTTON10                    1024
#define IDC_BUTTON11                    1025
#define IDC_BUTTON12                    1026
#define IDC_MK30COMMCTRL1               1027
#define IDC_EDIT9                       1028
#define IDC_BUTTON13                    1029
#define IDC_BUTTON_LOGEND               1030
#define IDC_OCX_VERSION                 1031
#define IDC_BUTTON15                    1032
#define IDC_BUTTON14                    1033
#define IDC_BUTTON_LOGSTART             1033
#define IDC_BN_GET_VOLTAGE              1034
#define IDC_BN_GET_ELECTRICITY          1035
#define IDC_BN_GET_FREQUENCY            1036
#define IDC_BN_GET_F_SPEED              1037
#define IDC_EDIT_VOLTAGE                1038
#define IDC_EDIT_ELECTRICITY            1039
#define IDC_EDIT_FREQUENCY              1040
#define IDC_EDIT_F_SPEED                1041
#define IDC_CHECK_LOOP_RUN              1042
#define IDC_BN_GET_MAX_FREQUENCY        1043
#define IDC_EDIT_METHOD_RESULT          1044
#define IDC_BN_CLEAR_METHOD_MSG         1045
#define IDC_EDIT_MAX_FREQUENCY          1046
#define IDC_BN_GET_SIGON_MAX_FREQUENCY  1047
#define IDC_BN_CLEAR_EVENT_MSG          1048
#define IDC_EDIT_EVENT_RESULT           1049
#define IDC_EDIT_SIGON_MAX_FREQUENCY    1050
#define IDC_BN_GET_RESISITIVITY_1       1051
#define IDC_EDIT_RESISITIVITY_1         1052
#define IDC_BN_GET_RESISITIVITY_2       1053
#define IDC_EDIT_RESISITIVITY_2         1054
#define IDC_BN_GET_INCH                 1055
#define IDC_EDIT_INCH                   1056
#define IDC_BN_GET_DIGIT                1057
#define IDC_EDIT_DIGIT                  1058
#define IDC_BN_GET_10989                1059
#define IDC_BN_GET_COORD_ORG            1060
#define IDC_EDIT_GET_COORD_ORG          1061
#define IDC_BN_GET_COORD_SYS            1062
#define IDC_BN_GET_MACH_COORD           1063
#define IDC_BN_GET_COORD                1064
#define IDC_EDIT_GET_COORD              1065
#define IDC_BN_POWER_ON                 1066
#define IDC_BUTTON_GetMachineKind       1067
#define IDC_BUTTON_GetCondition         1068
#define IDC_COMBO_DATABASE              1068
#define IDC_BTN_DoConditionSearch       1069
#define IDC_BTN_GET_COND_TYPE           1070
#define IDC_EDIT_COND_TYPE              1071
#define IDC_COMBO_PRESION               1072
#define IDC_STATIC_COND_NUM             1073
#define IDC_EDIT_RESEARCH_NUM           1074
#define IDC_BTN_GET_MACHINELOCK         1075
#define IDC_EDIT1_GETMACHINE            1076
#define IDC_EDIT_GET_MACHINELOCK        1076
#define IDC_EDIT_OFFSET_NUMBER          1078
#define IDC_EDIT_OFFSET_VALUE           1079
#define IDC_EDIT_MACRO_NUMBER           1080
#define IDC_EDIT_MACRO_VALUE            1081
#define IDC_BTN_GET_OFFSETVAR           1082
#define IDC_BTN_SET_MACROVAR            1083
#define IDC_EDIT_GET_MACRO_NUMBER       1084
#define IDC_EDIT_GET_MACRO_VALUE        1085
#define IDC_BTN_GET_MACROVAR            1086
#define IDC_STATIC_StartNo              1087
#define IDC_EDIT_GET_MACROVAR_STARTNO   1088
#define IDC_EDIT_GET_MACROVAR_ENDNO     1089
#define IDC_STATIC_EndNo                1090
#define IDC_BTN_GET_MACROVAR_RANGE      1091
#define IDC_BTN_GET_MACROVAR_SAFEARRAY  1092
#define IDC_BTN_SET_MACROVAR_RANGE      1093
#define IDC_GETRUNNINGFILENAME          1094
#define IDC_GETRUNNINGMAINNCFILEFIRSTLINE 1095
#define IDC_BTN_SET_MACROVAR_SAFEARRAY  1096
#define IDC_EDIT_SET_1STMACRO_VALUE     1097
#define IDC_STATIC_1STMACRO             1098

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
